import Providers from "@/store/providers";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "./components/MainNavigation/MainNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Face Detection App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MainNavigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
